tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
ports:
  - name: Backend
    port: 4567
    visibility: public
  - name: Frontend
    port: 3000
    visibility: public
vscode:
  extensions:
    - 42Crunch.vscode-openapi